### ISSUE TITLE
Use of clipboard

### ISSUE THREAD

**Issue by surbhitrao** [appgramming/LoneColor-Android#2]
Your code is working fine there was one issue of using clipboard,if user has some important information it will be overwritten  with the hex code.To solve this,comment these following lines.
In _Utils.java_

 
public static void copyText(Context context, CharSequence text) {
       final ClipboardManager clipboard = (ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
        final ClipData clip = ClipData.newPlainText(context.getString(R.string.app_name), text);
        clipboard.setPrimaryClip(clip);

and 

in _LoneColorActivty.java_

 Utils.copyText(this, Utils.colorToHex(color));
and 
Utils.copyText(this, e.toString());

**Comment by HelloWorldWriter2** [comment]
Sorry for the delay. Using the Clipboard is a documented feature of LoneColor:

> As a zero interface app (without any texts, buttons or settings), LoneColor gives you feedback using the... Clipboard. Just go and paste anywhere to get the color code of the random wallpaper, or any (unlikely) error messages.

The clipboard is by definition temporary, for short-term storage and transfer within apps. Do you find yourself often in the situation in which LoneColor overwrites your important information in the Clipboard?
